// <auto-generated />
using System;
using AppParque.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppParque.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoAtracciones.Domain.Atraccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int?>("AlturaMaxima")
                        .HasColumnType("integer");

                    b.Property<int?>("AlturaMinima")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Atracciones");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoAtracciones.Domain.AtraccionCondicionRestriccion", b =>
                {
                    b.Property<int>("AtraccionId")
                        .HasColumnType("integer");

                    b.Property<int>("CondicionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Permitido")
                        .HasColumnType("boolean");

                    b.HasKey("AtraccionId", "CondicionId");

                    b.HasIndex("CondicionId");

                    b.ToTable("AtraccionCondicionRestricciones");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoAtracciones.Domain.AtraccionGrupoRestriccion", b =>
                {
                    b.Property<int>("AtraccionId")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Permitido")
                        .HasColumnType("boolean");

                    b.HasKey("AtraccionId", "GrupoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("AtraccionGrupoRestricciones");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoGruposCondiciones.Domain.Condicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Condiciones");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoGruposCondiciones.Domain.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoPreguntas.Domain.OpcionRespuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PreguntaId");

                    b.ToTable("OpcionesRespuesta");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoPreguntas.Domain.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Evaluaciones.Domain.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Edad")
                        .HasColumnType("integer");

                    b.Property<int?>("Estatura")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("VisitanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VisitanteId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Evaluaciones.Domain.EvaluacionAtraccionResultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtraccionId")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("integer");

                    b.Property<bool>("PreseleccionadaAutomatica")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ValidadaPersonal")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AtraccionId");

                    b.HasIndex("EvaluacionId", "AtraccionId")
                        .IsUnique();

                    b.ToTable("EvaluacionAtraccionResultados");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Evaluaciones.Domain.EvaluacionCondicion", b =>
                {
                    b.Property<int>("EvaluacionId")
                        .HasColumnType("integer");

                    b.Property<int>("CondicionId")
                        .HasColumnType("integer");

                    b.HasKey("EvaluacionId", "CondicionId");

                    b.HasIndex("CondicionId");

                    b.ToTable("EvaluacionCondiciones");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Evaluaciones.Domain.EvaluacionGrupo", b =>
                {
                    b.Property<int>("EvaluacionId")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.HasKey("EvaluacionId", "GrupoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("EvaluacionGrupos");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Evaluaciones.Domain.EvaluacionRespuesta", b =>
                {
                    b.Property<int>("EvaluacionId")
                        .HasColumnType("integer");

                    b.Property<int>("OpcionRespuestaId")
                        .HasColumnType("integer");

                    b.HasKey("EvaluacionId", "OpcionRespuestaId");

                    b.HasIndex("OpcionRespuestaId");

                    b.ToTable("EvaluacionRespuestas");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Identidad.Domain.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revocado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Identidad.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Visitantes.Domain.Visitante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumento", "NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Visitantes");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoAtracciones.Domain.AtraccionCondicionRestriccion", b =>
                {
                    b.HasOne("AppParque.Api.Modules.CatalogoAtracciones.Domain.Atraccion", "Atraccion")
                        .WithMany("RestriccionesCondicion")
                        .HasForeignKey("AtraccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppParque.Api.Modules.CatalogoGruposCondiciones.Domain.Condicion", "Condicion")
                        .WithMany("AtraccionRestricciones")
                        .HasForeignKey("CondicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Condicion");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoAtracciones.Domain.AtraccionGrupoRestriccion", b =>
                {
                    b.HasOne("AppParque.Api.Modules.CatalogoAtracciones.Domain.Atraccion", "Atraccion")
                        .WithMany("RestriccionesGrupo")
                        .HasForeignKey("AtraccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppParque.Api.Modules.CatalogoGruposCondiciones.Domain.Grupo", "Grupo")
                        .WithMany("AtraccionRestricciones")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoPreguntas.Domain.OpcionRespuesta", b =>
                {
                    b.HasOne("AppParque.Api.Modules.CatalogoPreguntas.Domain.Pregunta", "Pregunta")
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Evaluaciones.Domain.Evaluacion", b =>
                {
                    b.HasOne("AppParque.Api.Modules.Identidad.Domain.Usuario", "Usuario")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppParque.Api.Modules.Visitantes.Domain.Visitante", "Visitante")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("VisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Evaluaciones.Domain.EvaluacionAtraccionResultado", b =>
                {
                    b.HasOne("AppParque.Api.Modules.CatalogoAtracciones.Domain.Atraccion", "Atraccion")
                        .WithMany("EvaluacionResultados")
                        .HasForeignKey("AtraccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppParque.Api.Modules.Evaluaciones.Domain.Evaluacion", "Evaluacion")
                        .WithMany("AtraccionResultados")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Evaluaciones.Domain.EvaluacionCondicion", b =>
                {
                    b.HasOne("AppParque.Api.Modules.CatalogoGruposCondiciones.Domain.Condicion", "Condicion")
                        .WithMany("EvaluacionCondiciones")
                        .HasForeignKey("CondicionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppParque.Api.Modules.Evaluaciones.Domain.Evaluacion", "Evaluacion")
                        .WithMany("Condiciones")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condicion");

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Evaluaciones.Domain.EvaluacionGrupo", b =>
                {
                    b.HasOne("AppParque.Api.Modules.Evaluaciones.Domain.Evaluacion", "Evaluacion")
                        .WithMany("Grupos")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppParque.Api.Modules.CatalogoGruposCondiciones.Domain.Grupo", "Grupo")
                        .WithMany("EvaluacionGrupos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluacion");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Evaluaciones.Domain.EvaluacionRespuesta", b =>
                {
                    b.HasOne("AppParque.Api.Modules.Evaluaciones.Domain.Evaluacion", "Evaluacion")
                        .WithMany("Respuestas")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppParque.Api.Modules.CatalogoPreguntas.Domain.OpcionRespuesta", "OpcionRespuesta")
                        .WithMany("EvaluacionRespuestas")
                        .HasForeignKey("OpcionRespuestaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluacion");

                    b.Navigation("OpcionRespuesta");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Identidad.Domain.RefreshToken", b =>
                {
                    b.HasOne("AppParque.Api.Modules.Identidad.Domain.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoAtracciones.Domain.Atraccion", b =>
                {
                    b.Navigation("EvaluacionResultados");

                    b.Navigation("RestriccionesCondicion");

                    b.Navigation("RestriccionesGrupo");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoGruposCondiciones.Domain.Condicion", b =>
                {
                    b.Navigation("AtraccionRestricciones");

                    b.Navigation("EvaluacionCondiciones");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoGruposCondiciones.Domain.Grupo", b =>
                {
                    b.Navigation("AtraccionRestricciones");

                    b.Navigation("EvaluacionGrupos");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoPreguntas.Domain.OpcionRespuesta", b =>
                {
                    b.Navigation("EvaluacionRespuestas");
                });

            modelBuilder.Entity("AppParque.Api.Modules.CatalogoPreguntas.Domain.Pregunta", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Evaluaciones.Domain.Evaluacion", b =>
                {
                    b.Navigation("AtraccionResultados");

                    b.Navigation("Condiciones");

                    b.Navigation("Grupos");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Identidad.Domain.Usuario", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("AppParque.Api.Modules.Visitantes.Domain.Visitante", b =>
                {
                    b.Navigation("Evaluaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
