using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text;
using System;
using System.Linq;
using AppParque.Shared;
using AppParque.Shared.Models;

namespace AppParque.Services
{
    public class FireBaseService
    {
        private readonly HttpClient _httpClient;
        private const string BaseUrl = "https://parque-del-cafe-c9303-default-rtdb.firebaseio.com/";

        public FireBaseService()
        {
            _httpClient = new HttpClient();
        }

        // Obtener todos los usuarios (si los manejas en Realtime DB)
        public async Task<Dictionary<string, User>> GetUserAsync()
        {
            var response = await _httpClient.GetAsync($"{BaseUrl}users.json");
            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                var users = JsonSerializer.Deserialize<Dictionary<string, User>>(json);
                return users;
            }
            return null;
        }

        // ✅ Registrar visitante en /visitantes
        public async Task<bool> AddVisitorAsync(DataUser visitante)
        {
            try
            {
                var json = JsonSerializer.Serialize(visitante);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsync($"{BaseUrl}visitantes.json", content);
                return response.IsSuccessStatusCode;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al agregar visitante: {ex.Message}");
                return false;
            }
        }

        // ✅ Guardar resultado de test en /tests/{uid}
        public async Task<bool> AddTestAsync(string uid, DataUser testResult)
        {
            try
            {
                var nurseUid = UsuarioGlobal.Uid;  // 🔹 Tomado desde el login
                var json = JsonSerializer.Serialize(testResult);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                // 🔹 Guardar bajo /tests/{nurseUid}/{autogeneratedId}
                var response = await _httpClient.PostAsync($"{BaseUrl}tests/{nurseUid}.json", content);
                return response.IsSuccessStatusCode;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al agregar test: {ex.Message}");
                return false;
            }
        }

        // ✅ Obtener tests (admin ve todos, user solo los suyos)
        public async Task<Dictionary<string, Dictionary<string, DataUser>>> GetTestsAsync(string uid, string role)
        {
            try
            {
                string url = role == "admin" ? $"{BaseUrl}tests.json" : $"{BaseUrl}tests/{uid}.json";
                var response = await _httpClient.GetAsync(url);
                if (!response.IsSuccessStatusCode)
                    return new Dictionary<string, Dictionary<string, DataUser>>();

                var json = await response.Content.ReadAsStringAsync();
                if (string.IsNullOrWhiteSpace(json) || json == "null")
                    return new Dictionary<string, Dictionary<string, DataUser>>();

                // Caso admin → estructura de 2 niveles
                Dictionary<string, Dictionary<string, DataUser>> twoLevel = null;
                try { twoLevel = JsonSerializer.Deserialize<Dictionary<string, Dictionary<string, DataUser>>>(json); } catch { }

                if (twoLevel != null && twoLevel.Count > 0 && twoLevel.Values.All(v => v != null))
                    return twoLevel;

                // Caso usuario → estructura de 1 nivel (envolvemos con UID real)
                Dictionary<string, DataUser> oneLevel = null;
                try { oneLevel = JsonSerializer.Deserialize<Dictionary<string, DataUser>>(json); } catch { }

                if (oneLevel != null)
                {
                    var safeUid = string.IsNullOrWhiteSpace(uid) ? "unknown" : uid;
                    return new Dictionary<string, Dictionary<string, DataUser>>
                    {
                        { safeUid, oneLevel }
                    };
                }

                return new Dictionary<string, Dictionary<string, DataUser>>();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error en GetTestsAsync: {ex.Message}");
                return new Dictionary<string, Dictionary<string, DataUser>>();
            }
        }

        public async Task<Dictionary<string, Attraction>> GetAttractionsAsync()
        {
            var response = await _httpClient.GetAsync($"{BaseUrl}atracciones.json");
            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                var attractions = JsonSerializer.Deserialize<Dictionary<string, Attraction>>(json);
                return attractions;
            }
            return null;
        }

        public async Task<Dictionary<string, string>> GetResourcesAsync()
        {
            try
            {
                // Cambiar la URL para obtener el nodo resources completo
                var response = await _httpClient.GetAsync($"{BaseUrl}resources.json");
                if (!response.IsSuccessStatusCode)
                    return null;

                var json = await response.Content.ReadAsStringAsync();

                // Deserializar a un objeto que contenga la propiedad images
                var resourcesWrapper = JsonSerializer.Deserialize<ResourcesWrapper>(json);
                return resourcesWrapper?.images;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error obteniendo resources: {ex.Message}");
                return null;
            }
        }

        // Clase wrapper para la estructura JSON
        private class ResourcesWrapper
        {
            [JsonPropertyName("images")]
            public Dictionary<string, string> images { get; set; }
        }

        public async Task<bool> TestConnectionAsync()
        {
            try
            {
                var response = await _httpClient.GetAsync($"{BaseUrl}users.json");
                return response.IsSuccessStatusCode;
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error al conectar con Firebase: " + ex.Message);
                return false;
            }
        }
    }
}
